version: '3.8'

networks:
  mandarine-dev-net:

volumes:
  mandarine-dev-postgres-data:
  mandarine-dev-redis-data:
  mandarine-dev-minio-data:

services:
  ################################
  ########## PostgreSQL ##########
  ################################
  postgres:
    image: postgis/postgis:17-3.4-alpine
    container_name: mandarine-dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - mandarine-dev-postgres-data:/var/lib/postgresql/data
    networks:
      - mandarine-dev-net

  ###########################
  ########## Redis ##########
  ###########################
  redis:
    image: redis/redis-stack:7.4.0-v0
    container_name: mandarine-dev-redis
    restart: unless-stopped
    environment:
      REDIS_USER: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
    ports:
      - ${REDIS_PORT}:6379
      - ${REDIS_UI_PORT}:8001
    volumes:
      - mandarine-dev-redis-data:/data
    networks:
      - mandarine-dev-net

  ###########################
  ########## Minio ##########
  ###########################
  minio:
    image: bitnami/minio:2024.8.3
    container_name: mandarine-dev-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESSKEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRETKEY}
      MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKETS}
    healthcheck:
      test: [ "CMD-SHELL", "mc ready local" ]
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_UI_PORT}:9001
    volumes:
      - mandarine-dev-minio-data:/bitnami/minio/data
    networks:
      - mandarine-dev-net

  #################################
  ######### Reverse Proxy #########
  #################################
  reverse-proxy:
    image: nginx:1.27.2-alpine3.20-slim
    container_name: mandarine-dev-reverse-proxy
    restart: unless-stopped
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: [ 'CMD-SHELL', 'nc -z localhost 80 || exit 1' ]
    ports:
      - ${REVERSE_PROXY_PORT}:80
    networks:
      - mandarine-dev-net